### ISSUE TITLE
Learn classes

### ISSUE THREAD

**Issue by bdshadow** [AliceMillers/python#3]
read about classes:
- http://pythonprogramminglanguage.com/class/
- http://ru.diveintopython.net/fileinfo_class.html

0) switch to branch master
0a) create branch `learn_classes`

1) in file `person.py` create class Person
2) add `name` and `age` fields inside this class
3)  `__init__` should accept 2 arguments: `name` and `age` and set there values to the fields from 2)
4) add method `say_hello` which prints: "Hi, i'm <name>. My age is <age>"

5) in file `group.py` create class Group
6) add array `people` as a class
7) add method `add_person`, which has one argument `person` and adds it to the array `people` from 6)
8) add method `say_hello`. It should print  "Hi, i'm <name>. My age is <age>"  of all added persons

9) create `test.py`script
10) run the following code:

``` python
import Person
import Group

group = Group()
group.add_person(Person("Dmitry", 24))
group.add_person(Person("Yulia", 24))
group.say_hello()
```

it should print:

```
Hi, i'm Dmitry. My age is 24
Hi, i'm Yulia. My age is 24
```

11) push branch `learn_classes`: `git push origin learn_classes`

**Comment by AliceMillers** [comment]
6. add array people as a class variable
I got it.
